### ISSUE TITLE
Inclusão de novos estilos

### ISSUE THREAD

**Issue by Lucasfog** [tihhgoncalves/WhatsFloat.js#2]
Acredito que seria bastante vantajoso incorporar a funcionalidade de selecionar múltiplos estilos de ícones, de modo a atender às diversas necessidades das interfaces de usuário. Essa opção proporcionaria uma maior flexibilidade e personalização, permitindo uma adaptação mais eficaz a diferentes contextos e preferências de design.

**Comment by tihhgoncalves** [comment]
Olá @Lucasfog, primeiramente, muito obrigado pela sua excelente sugestão!

Sua ideia de múltiplos estilos de ícones realmente adiciona valor. Estou animado para informar que já estamos considerando isso e planejamos introduzir essa funcionalidade em breve. Fique de olho nas atualizações! 🖖🏻

**Comment by tihhgoncalves** [comment]
Olá @Lucasfog, trago boas novas!

Foi implementado a sua sugestão de disponibilizar opções de ícones CTA.
Já está disponível no release 1.2.0, confere aí:
https://github.com/tihhgoncalves/WhatsFloat.js/releases/tag/1.2.0

Até breve! 🖖🚀

**Comment by tihhgoncalves** [comment]
Olá @Lucasfog , trago boas novas! 🚀

Foi implementado a sua sugestão de disponibilizar opções de ícones CTA.
Já está disponível na versão 1.2.0, confira aí:
https://github.com/tihhgoncalves/WhatsFloat.js/releases/tag/1.2.0

Até breve! 🖖

**Comment by Lucasfog** [comment]
Olá, @tihhgoncalves ! Ficou muito bom ! agradeço por ter incorporado minha sugestão ao projeto! Sucesso!!!

**Comment by tihhgoncalves** [comment]
Eu que agradeço a sua colaboração, @Lucasfog .
Boas ideias são sempre bem-vindas :)
